-   repo: https://github.com/pre-commit/mirrors-autopep8.git
    sha: v1.3.1
    hooks:
    -   id: autopep8

# -   repo: https://github.com/pre-commit/pre-commit-hooks.git
#     sha: v0.7.1
#     hooks:
#     -   id: flake8
#         include: src/
